fix databases path
bcgov/clamav-mirror pull request #11
Opened 2022-08-22 01:53 UTC by eduardocerqueira

databases path wasn't being created during initialtization or even during the first run by cvd config set.

Current contents in /mnt/cvdupdate/databases directory...
ls: /mnt/cvdupdate/databases: No such file or directory

# Description

## Types of changes

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2022-08-22 20:10 UTC, jujaga requested changes
Thank you for your PR - very good find. Please do a minor casing fix on the echo command and we can get this merged in. Thanks! 👍

2022-08-22 20:10 UTC, jujaga commented on docker/src/entrypoint.sh
> +      echo "creating $CVD_DIR/databases folder"
Please capitalize C on Creating.

2022-08-25 15:52 UTC, eduardocerqueira commented on docker/src/entrypoint.sh
> +      echo "creating $CVD_DIR/databases folder"
sure! just changed it!

2022-08-25 19:19 UTC, jujaga approved these changes

2022-08-25 19:21 UTC, merged